In [1]:
import plotly
import numpy as np 
import pandas as pd
import plotly.express as px
import matplotlib.pyplot as plt
import os
import glob
#from tqdm import tqdm

In [2]:
df=pd.read_pickle("result.pkl")
df

pdb  \
0        /project/zerze/ayushg/argonne/configs/ICs/Q_0....   
1        /project/zerze/ayushg/argonne/configs/ICs/Q_0....   
2        /project/zerze/ayushg/argonne/configs/ICs/Q_0....   
3        /project/zerze/ayushg/argonne/configs/ICs/Q_0....   
4        /project/zerze/ayushg/argonne/configs/ICs/Q_0....   
...                                                    ...   
1350995  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...   
1350996  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...   
1350997  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...   
1350998  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...   
1350999  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...   

                                                       dcd  frame      rmsd  \
0        /project/zerze/ayushg/argonne/ddmd/rna8/test/m...      0  4.029846   
1        /project/zerze/ayushg/argonne/ddmd/rna8/test/m...      1  4.007001   
2        /project/zerze/ayushg/argonne/ddmd/rna8/test/m...      2  4.171796   
3        /project/zerze/ayushg/argonne/ddmd/rna8/test/m...      3  4.136606   
4        /project/zerze/ayushg/argonne/ddmd/rna8/test/m...      4  4.180786   
...                                                    ...    ...       ...   
1350995  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    995  5.865321   
1350996  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    996  5.910218   
1350997  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    997  5.929921   
1350998  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    998  5.913985   
1350999  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    999  5.719712   

                Q                                         embeddings  \
0        0.513320  [0.6582605242729187, -1.203732967376709, 0.378...   
1        0.545773  [0.7967053651809692, -1.0128430128097534, 0.69...   
2        0.569993  [0.7967053651809692, -1.0128430128097534, 0.69...   
3        0.506452  [0.9914444088935852, -0.8519664406776428, 0.26...   
4        0.478177  [0.7967053651809692, -1.0128430128097534, 0.69...   
...           ...                                                ...   
1350995  0.001049  [-0.25612249970436096, -0.39776310324668884, -...   
1350996  0.000161  [-0.02384806051850319, -0.8938273191452026, -0...   
1350997  0.004852  [-0.02384806051850319, -0.8938273191452026, -0...   
1350998  0.008335  [-0.02384806051850319, -0.8938273191452026, -0...   
1350999  0.000347  [-0.1899455040693283, -0.26780498027801514, -0...   

         lof_score            sys_label gpu_id  cluster_label  
0             -1.0  md_run_2_1697113447      2            172  
1             -1.0  md_run_2_1697113447      2             59  
2             -1.0  md_run_2_1697113447      2             59  
3             -1.0  md_run_2_1697113447      2            476  
4             -1.0  md_run_2_1697113447      2             59  
...            ...                  ...    ...            ...  
1350995        0.0  md_run_7_1697713771      7             81  
1350996       -1.0  md_run_7_1697713771      7            319  
1350997       -1.0  md_run_7_1697713771      7            319  
1350998       -1.0  md_run_7_1697713771      7            319  
1350999        0.0  md_run_7_1697713771      7             81  

[1351000 rows x 10 columns]

In [3]:
mis_df=df[(df.rmsd<4) & (df.rmsd>3) & (df.Q>0.9)]   # misfolded configs
mis_df

pdb  \
911      /project/zerze/ayushg/argonne/configs/ICs/Q_0....   
2483     /project/zerze/ayushg/argonne/configs/ICs/Q_0....   
2486     /project/zerze/ayushg/argonne/configs/ICs/Q_0....   
3059     /project/zerze/ayushg/argonne/ddmd/rna8/test/m...   
3063     /project/zerze/ayushg/argonne/ddmd/rna8/test/m...   
...                                                    ...   
1132995  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...   
1132996  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...   
1132997  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...   
1132998  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...   
1132999  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...   

                                                       dcd  frame      rmsd  \
911      /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    911  3.204375   
2483     /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    483  3.192852   
2486     /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    486  3.289175   
3059     /project/zerze/ayushg/argonne/ddmd/rna8/test/m...     59  3.995156   
3063     /project/zerze/ayushg/argonne/ddmd/rna8/test/m...     63  3.983279   
...                                                    ...    ...       ...   
1132995  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    995  3.536608   
1132996  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    996  3.479539   
1132997  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    997  3.696448   
1132998  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    998  3.770333   
1132999  /project/zerze/ayushg/argonne/ddmd/rna8/test/m...    999  3.699160   

                Q                                         embeddings  \
911      0.940599  [0.651121973991394, -0.7338123917579651, 0.441...   
2483     0.901038  [0.9759169816970825, -0.44861283898353577, 0.7...   
2486     0.900781  [0.651121973991394, -0.7338123917579651, 0.441...   
3059     0.927959  [0.8403105139732361, -1.081087589263916, 0.378...   
3063     0.902304  [0.5155405402183533, -0.8279011249542236, 0.37...   
...           ...                                                ...   
1132995  0.979679  [0.46087366342544556, -0.7028083205223083, 0.0...   
1132996  0.937197  [0.7261608839035034, -0.43459412455558777, 0.2...   
1132997  0.966087  [0.8562688231468201, -0.4113013744354248, 0.67...   
1132998  0.961682  [0.8922640085220337, -0.6066605448722839, 0.34...   
1132999  0.978015  [0.9759169816970825, -0.44861283898353577, 0.7...   

         lof_score            sys_label gpu_id  cluster_label  
911      -1.000000  md_run_2_1697113447      2            327  
2483     -1.000000  md_run_2_1697118671      2            114  
2486     -1.000000  md_run_2_1697118671      2            327  
3059     -1.000000  md_run_2_1697121277      2            468  
3063     -1.000000  md_run_2_1697121277      2            468  
...            ...                  ...    ...            ...  
1132995  -0.997835  md_run_7_1697129027      7            161  
1132996  -1.000000  md_run_7_1697129027      7            104  
1132997  -1.000000  md_run_7_1697129027      7            114  
1132998  -1.000000  md_run_7_1697129027      7            468  
1132999  -1.000000  md_run_7_1697129027      7            114  

[5943 rows x 10 columns]

In [4]:
embed=np.array(mis_df['embeddings'].values.tolist())
embed[3000]

array([ 0.75612116, -0.36318207,  0.5595175 ,  0.30643007, -0.09311191,
        0.59009695])

In [5]:
from sklearn.cluster import KMeans, MiniBatchKMeans

kmeans = MiniBatchKMeans(
            n_clusters=100, 
            init="k-means++", random_state=42
        ).fit(embed)

/project/dsi/apps/python/3.9/lib/python3.9/site-packages/sklearn/cluster/_kmeans.py:870: FutureWarning: The default value of `n_init` will change from 3 to 'auto' in 1.4. Set the value of `n_init` explicitly to suppress the warning
  warnings.warn(
Exception ignored on calling ctypes callback function: <function _ThreadpoolInfo._find_modules_with_dl_iterate_phdr.<locals>.match_module_callback at 0x1467737295e0>
Traceback (most recent call last):
  File "/project/dsi/apps/python/3.9/lib/python3.9/site-packages/threadpoolctl.py", line 400, in match_module_callback
    self._make_module_from_path(filepath)
  File "/project/dsi/apps/python/3.9/lib/python3.9/site-packages/threadpoolctl.py", line 515, in _make_module_from_path
    module = module_class(filepath, prefix, user_api, internal_api)
  File "/project/dsi/apps/python/3.9/lib/python3.9/site-packages/threadpoolctl.py", line 606, in __init__
    self.version = self.get_version()
  File "/project/dsi/apps/python/3.9/lib/python3.9/site-p

#### Get the representative points i.e. the points closest to the biggest cluster centroid

In [6]:
# Get cluster labels and centers
labels = kmeans.labels_
centroids = kmeans.cluster_centers_

# Count the number of data points in each cluster
cluster_sizes = np.bincount(labels)

# Find the label of the largest cluster
largest_cluster_label = np.argmax(cluster_sizes)

# Find the centroid of the largest cluster
largest_cluster_centroid = centroids[largest_cluster_label]

# Find the indices of data points in the largest cluster
largest_points_indices = np.where(labels == largest_cluster_label)[0]

# Get the actual data points in the largest cluster
points = embed[largest_points_indices]

# Calculate the distances from each data point in the largest cluster to the centroid
distances_to_largest_centroid = np.linalg.norm(embed - largest_cluster_centroid, axis=1)

# Find the indices of data points closest to the largest cluster's centroid
closest_points_indices = np.argsort(distances_to_largest_centroid)
print(f"Indices of closest points:{closest_points_indices}")

# Get the actual data points closest to the centroid
closest_points = embed[closest_points_indices]

print(len(closest_points))
print(f"Label of the largest cluster: {largest_cluster_label}")
print(f"Points in the largest cluster:\n{closest_points}")

Indices of closest points:[3851 3852 3853 ...  153  155 5804]
5943
Label of the largest cluster: 31
Points in the largest cluster:
[[ 0.65112197 -0.73381239  0.44160676  0.20206894  0.30830574  0.4322122 ]
 [ 0.65112197 -0.73381239  0.44160676  0.20206894  0.30830574  0.4322122 ]
 [ 0.65112197 -0.73381239  0.44160676  0.20206894  0.30830574  0.4322122 ]
 ...
 [ 0.88242763 -0.4069581   0.48802292  0.66424358 -0.70693606 -1.09445453]
 [ 0.88242763 -0.4069581   0.48802292  0.66424358 -0.70693606 -1.09445453]
 [ 0.89368397 -1.83163142  0.93824172  0.09195487 -0.36613846 -1.0173918 ]]


In [7]:
closest_points_indices[:4]     # representative misfolded configs: the first few points closest to the largest cluster centroid

array([3851, 3852, 3853, 3854])

In [8]:
closest_points_indices[0]

3851

#### Clustering using mdtraj

In [7]:
for index, row in mis_df.iterrows():
    print(row['frame'])
    
import mdtraj as md
traj=[]
for index, row in mis_df.iterrows():
    traj.append(md.load_frame(row['dcd'],row['frame'],top=row['pdb']))
    print(index)
print(traj)

157458
212802
212803
212804
212805
212806
212807
212808
212809
212810
212811
212812
212813
212814
212815
212816
212817
212818
212819
212820
212821
212822
212823
212824
212825
212826
212827
212828
212829
212830
212831
212832
212833
212834
212835
212836
212837
212838
212839
212840
212841
212842
212843
212844
212845
212846
212847
212848
212849
212850
212851
212852
212853
212854
212855
212856
212857
212858
212859
212860
212861
212862
212863
212864
212865
212866
212867
212868
212869
212870
212871
212872
212873
212874
212875
212876
212877
212878
212879
212880
212881
212882
212883
212884
212885
212887
212888
212893
212913
212917
212919
212921
212922
212923
212924
212925
212926
212927
212928
212929
212930
212931
212932
212933
212934
212935
212936
212937
212938
212939
212940
212941
212942
212943
212944
212945
212946
212947
212948
212949
212950
212951
212952
212953
212954
212955
212956
212957
212958
212959
212960
212961
212962
212963
212964
212965
212971
212982
212983
212984
212985
212986
212987

: 

In [ ]:
# compute all pairwise rmsds between conformations
atom_indices = [a.index for a in traj.topology.atoms if a.element.symbol != 'H']
distances = np.empty((traj.n_frames, traj.n_frames))
for i in range(traj.n_frames):
    distances[i] = md.rmsd(traj, traj, i, atom_indices=atom_indices)

# Transform these distances into similarity scores and determine the centroid
beta = 1
index = np.exp(-beta*distances / distances.std()).sum(axis=1).argmax()
print(index)
centroid = traj[index]
print(centroid)

In [9]:
import MDAnalysis as mda
import barnaba as bb
from barnaba import definitions

In [10]:
pdb_file=df.iloc[0]['pdb']

In [7]:

# folded
folded=df.iloc[2472]
fol=mda.Universe(folded['pdb'],folded['dcd'])
fol.trajectory[folded['frame']]
fol.atoms.write('folded.pdb')

/home/agupta55/.local/lib/python3.9/site-packages/MDAnalysis/coordinates/PDB.py:1151: UserWarning: Found no information for attr: 'altLocs' Using default value of ' '
  warnings.warn("Found no information for attr: '{}'"
/home/agupta55/.local/lib/python3.9/site-packages/MDAnalysis/coordinates/PDB.py:1151: UserWarning: Found no information for attr: 'icodes' Using default value of ' '
  warnings.warn("Found no information for attr: '{}'"
/home/agupta55/.local/lib/python3.9/site-packages/MDAnalysis/coordinates/PDB.py:1151: UserWarning: Found no information for attr: 'chainIDs' Using default value of ''
  warnings.warn("Found no information for attr: '{}'"
/home/agupta55/.local/lib/python3.9/site-packages/MDAnalysis/coordinates/PDB.py:1151: UserWarning: Found no information for attr: 'occupancies' Using default value of '1.0'
  warnings.warn("Found no information for attr: '{}'"
/home/agupta55/.local/lib/python3.9/site-packages/MDAnalysis/coordinates/PDB.py:1151: UserWarning: Found no inf

In [11]:
# misfolded
misfolded=mis_df.iloc[closest_points_indices[0]]
mfol=mda.Universe(misfolded['pdb'],misfolded['dcd'])
mfol.trajectory[misfolded['frame']]
mfol.atoms.write('misfolded.gro')

/home/agupta55/.local/lib/python3.9/site-packages/MDAnalysis/coordinates/DCD.py:165: DeprecationWarning: DCDReader currently makes independent timesteps by copying self.ts while other readers update self.ts inplace. This behavior will be changed in 3.0 to be the same as other readers. Read more at https://github.com/MDAnalysis/mdanalysis/issues/3889 to learn if this change in behavior might affect you.
  warnings.warn("DCDReader currently makes independent timesteps"


In [13]:
# annotate for misfolded
pdb = "misfolded.pdb" 
stackings, pairings, res = bb.annotate(pdb)
# list base pairings 
print("BASE-PAIRS") 
for p in range(len(pairings[0][0])): 
    res1 = res[pairings[0][0][p][0]] 
    res2 = res[pairings[0][0][p][1]] 
    interaction = pairings[0][1][p] 
    print("%10s %10s %4s" % (res1,res2,interaction))
# list base-stackings 
print() 
print("STACKING") 
for p in range(len(stackings[0][0])): 
    res1 = res[stackings[0][0][p][0]] 
    res2 = res[stackings[0][0][p][1]] 
    interaction = stackings[0][1][p] 
    print("%10s %10s %4s" % (res1,res2,interaction))

# calculate backbone angles  
angles,res = bb.backbone_angles(pdb)
# print angles 
header = "# Residue " + "".join(["%10s " % aa for aa in definitions.bb_angles]) 
print(header) 
for j in range(angles.shape[1]): 
    stri = "%10s" % res[j] 
    for k in range(angles.shape[2]): 
        stri += "%10.3f " % angles[0,j,k]
    print(stri)

# Loading misfolded.pdb 
# Skipping unknown residue Na+11 
# Skipping unknown residue Na+12 
# Skipping unknown residue Na+13 
# Skipping unknown residue Na+14 
# Skipping unknown residue Na+15 
# Skipping unknown residue Na+16 
# Skipping unknown residue Na+17 
# Skipping unknown residue Na+18 
# Skipping unknown residue Na+19 
# Skipping unknown residue Na+20 
# Skipping unknown residue Na+21 
# Skipping unknown residue Na+22 
# Skipping unknown residue Na+23 
# Skipping unknown residue Na+24 
# Skipping unknown residue Na+25 
# Skipping unknown residue Na+26 
# Skipping unknown residue Na+27 
# Skipping unknown residue Na+28 
# Skipping unknown residue Na+29 
# Skipping unknown residue Na+30 
# Skipping unknown residue Na+31 
# Skipping unknown residue Na+32 
# Skipping unknown residue Na+33 
# Skipping unknown residue Na+34 
# Skipping unknown residue Na+35 
# Skipping unknown residue Na+36 
# Skipping unknown residue Na+37 
# Skipping unknown residue Na+38 
# Skipping unknown resi

BASE-PAIRS
    G5_1_0    C3_10_0  WCc
     G_2_0      C_9_0  WCc
     C_3_0      G_8_0  WCc

STACKING
    G5_1_0      G_2_0   >>
     G_2_0      C_3_0   >>
     G_4_0      A_5_0   >>
     A_5_0      G_6_0   >>
     G_8_0      C_9_0   >>
     C_9_0    C3_10_0   >>
# Residue      alpha       beta      gamma      delta        eps       zeta        chi 
    G5_1_0       nan        nan      1.381      1.310     -2.988     -1.263     -2.663 
     G_2_0    -1.508     -3.091      1.161      1.163     -2.543     -1.343     -2.820 
     C_3_0    -1.025      2.595      1.089      1.271     -1.861     -1.682     -2.985 
     G_4_0     1.194      1.772      3.104      1.643     -2.538     -0.927      3.092 
     A_5_0    -1.344     -2.907      0.798      1.636     -2.782     -1.044     -2.458 
     G_6_0    -1.488      2.924      1.019      1.367     -2.440     -1.151     -2.774 
     A_7_0    -1.091      2.923      1.023      1.304     -2.474     -0.852     -3.080 
     G_8_0    -1.108      2.843 

# Loading misfolded.pdb 
# Skipping unknown residue Na+11 
# Skipping unknown residue Na+12 
# Skipping unknown residue Na+13 
# Skipping unknown residue Na+14 
# Skipping unknown residue Na+15 
# Skipping unknown residue Na+16 
# Skipping unknown residue Na+17 
# Skipping unknown residue Na+18 
# Skipping unknown residue Na+19 
# Skipping unknown residue Na+20 
# Skipping unknown residue Na+21 
# Skipping unknown residue Na+22 
# Skipping unknown residue Na+23 
# Skipping unknown residue Na+24 
# Skipping unknown residue Na+25 
# Skipping unknown residue Na+26 
# Skipping unknown residue Na+27 
# Skipping unknown residue Na+28 
# Skipping unknown residue Na+29 
# Skipping unknown residue Na+30 
# Skipping unknown residue Na+31 
# Skipping unknown residue Na+32 
# Skipping unknown residue Na+33 
# Skipping unknown residue Na+34 
# Skipping unknown residue Na+35 
# Skipping unknown residue Na+36 
# Skipping unknown residue Na+37 
# Skipping unknown residue Na+38 
# Skipping unknown resi